//: spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.
welcome:
  message: Welcome To Department
---
server:
  error:
    include-message: always
  port: 9001
---
spring:
  application:
    name: DEPARTMENT-SERVICE
---
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
---
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=yes&characterEncoding=UTF-8
    password: ''
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'


